version: '3'

networks:
  laravel_network:

services:
  app:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: ${CONTAINERS_PREFIX}_app
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./src:/var/www/html:delegated
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - php
      - redis
      - mysql
    networks:
      - laravel_network

  mysql:
    image: mariadb:10.6
    restart: unless-stopped
    tty: true
    container_name: ${CONTAINERS_PREFIX}_mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel_network

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.root.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: ${CONTAINERS_PREFIX}_php
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel_network

  redis:
    image: redis:alpine
    container_name: laravel_network_redis
    restart: unless-stopped
    networks:
      - laravel_network

  composer:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: ${CONTAINERS_PREFIX}_composer
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    networks:
      - laravel_network

  npm:
    image: node:current-alpine
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    container_name: larave_npm
    entrypoint: [ 'npm' ]
    networks:
      - laravel_network

  artisan:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: ${CONTAINERS_PREFIX}_artisan
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${CONTAINERS_PREFIX}_pma
    hostname: PhpMyAdmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - ${PMA_PORT}:80
    networks:
      - laravel_network

